enigme:source.o main.o
	gcc source.o main.o -o enigme -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
source.o:source.c
	gcc -c source.c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf


