prog:main.o background.o perso.o enemie.o enigme1.o source.o minimap.o Backg.o Buttons.o texte.o intro.o 
	gcc perso.o main.o source.o background.o enemie.o enigme1.o minimap.o Backg.o Buttons.o texte.o intro.o  -o prog -lSDL_image -lSDL_ttf -lSDL_mixer -lSDL
main.o:main.c 
	gcc -c main.c 
background.o:background.c
	gcc -c background.c
perso.o:perso.c
	gcc -c perso.c -g 
enemie.o:enemie.c 
	gcc -c enemie.c
enigme1.o:enigme1.c 
	gcc -c enigme1.c
source.o:source.c 
	gcc -c source.c
minimap.o:minimap.c 
	gcc -c minimap.c
Backg.o:Backg.c
	gcc -c Backg.c -g
Buttons.o:Buttons.c
	gcc -c Buttons.c -g
texte.o:texte.c
	gcc -c texte.c -g
intro.o:intro.c
	gcc -c intro.c -g
 
